"""Sidebar component for GeoScout."""

import streamlit as st


def render_sidebar() -> None:
    """Render the research sidebar with workflow, dataset, and scope info."""
    with st.sidebar:
        st.markdown(
            "<h2 style='font-size: 1.3rem; margin-bottom: 4px;'>About GeoScout</h2>",
            unsafe_allow_html=True,
        )
        st.caption("Evidence-Grounded Architecture for GeoAI")

        st.markdown(
            """
**GeoScout** explores an evidence-grounded architecture where language models orchestrate
deterministic GIS computation while preserving strict traceability.

#### Core Workflow
1. **Research Question**
2. **Agent Tool Selection**
3. **Deterministic GIS Execution**
4. **Evidence Collection**
5. **Grounded Answer**
6. **Spatial Visualization**

#### Design Principle
- **Language Model:** Handles query interpretation and tool orchestration.
- **Deterministic GIS:** Produces measurable spatial evidence.
"""
        )

        st.divider()

        st.markdown(
            "<h3 style='font-size: 1.1rem;'>Dataset Specification</h3>",
            unsafe_allow_html=True,
        )
        st.markdown(
            """
- **Type:** Synthetic vegetation-change grid
- **Domain:** Environmental monitoring
- **Spatial units:** 100 uniform cells (10 × 10)
- **Temporal span:** 2020 (Baseline) → 2025 (Current)
- **CRS:** `EPSG:4326` (WGS84)
- **Degradation threshold:** $\\Delta \\text{NDVI} \\le -0.10$
"""
        )

        st.divider()

        st.markdown(
            "<h3 style='font-size: 1.1rem;'>Research Scope</h3>",
            unsafe_allow_html=True,
        )
        st.caption(
            "This interface is an observability and demonstration layer over the frozen "
            "GeoScout v3 experimental baseline. It does not independently verify every "
            "natural-language claim generated by the language model."
        )
